// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;

namespace Pulumi.AzureAD
{
    internal class ResourcePackage : IResourcePackage
    {
        public string Name => "azuread";

        public string? Version => Utilities.Version;

        [Obsolete("The overload with 4 parameters is deprecated and will be removed")]
        public ProviderResource ConstructProvider(string name, string type, System.Collections.Generic.IDictionary<string, object?>? args, string urn)
            => ConstructProvider(name, type, urn);

        public ProviderResource ConstructProvider(string name, string type, string urn)
        {
            if (type == "pulumi:providers:azuread")
                return new Provider(name, default!, new CustomResourceOptions {Urn=urn});
            throw new Exception($"Unknown provider type {type}");
        }

        public Resource Construct(string name, string type, string urn)
        {
            var options = new CustomResourceOptions {Urn=urn};
            switch (type)
            {
                case "azuread:index/application:Application":
                    return new Pulumi.AzureAD.Application(name, default!, options);
                case "azuread:index/applicationCertificate:ApplicationCertificate":
                    return new Pulumi.AzureAD.ApplicationCertificate(name, default!, options);
                case "azuread:index/applicationPassword:ApplicationPassword":
                    return new Pulumi.AzureAD.ApplicationPassword(name, default!, options);
                case "azuread:index/group:Group":
                    return new Pulumi.AzureAD.Group(name, default!, options);
                case "azuread:index/groupMember:GroupMember":
                    return new Pulumi.AzureAD.GroupMember(name, default!, options);
                case "azuread:index/servicePrincipal:ServicePrincipal":
                    return new Pulumi.AzureAD.ServicePrincipal(name, default!, options);
                case "azuread:index/servicePrincipalCertificate:ServicePrincipalCertificate":
                    return new Pulumi.AzureAD.ServicePrincipalCertificate(name, default!, options);
                case "azuread:index/servicePrincipalPassword:ServicePrincipalPassword":
                    return new Pulumi.AzureAD.ServicePrincipalPassword(name, default!, options);
                case "azuread:index/user:User":
                    return new Pulumi.AzureAD.User(name, default!, options);
            }
            throw new Exception($"Unknown resource type {type}");
        }
    }
}
